export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SAVE_EDITED_TASK = 'SAVE_EDITED_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const ADD_TASK_TITLE_CHANGED = 'ADD_TASK_TITLE_CHANGED';
export const ADD_TASK_DESC_CHANGED = 'ADD_TASK_DESC_CHANGED';
export const EDIT_TASK_TITLE_CHANGED = 'EDIT_TASK_TITLE_CHANGED';
export const EDIT_TASK_DESC_CHANGED = 'EDIT_TASK_DESC_CHANGED';
export const UPDATE_EDIT_DATA = 'UPDATE_EDIT_DATA';


export default { ADD_TASK, ADD_TASK_TITLE_CHANGED, ADD_TASK_DESC_CHANGED, DELETE_TASK, EDIT_TASK_TITLE_CHANGED, EDIT_TASK_DESC_CHANGED, SAVE_EDITED_TASK, UPDATE_EDIT_DATA, COMPLETE_TASK }